package com.myboot.demo.dao;

import com.myboot.demo.entity.InterfaceTabl;
import java.util.List;

public interface InterfaceTablMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_tabl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long interfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_tabl
     *
     * @mbggenerated
     */
    int insert(InterfaceTabl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_tabl
     *
     * @mbggenerated
     */
    InterfaceTabl selectByPrimaryKey(Long interfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_tabl
     *
     * @mbggenerated
     */
    List<InterfaceTabl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_tabl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InterfaceTabl record);
}